spring:
  application:
    name: "sb2-observability"

management:
  endpoints:
    web:
      exposure:
        include: "metrics"
  metrics:
    export:
      stackdriver:
        enabled: true
        project-id: "YOUR_PROJECT_ID"
        resource-type: "global"
    enable:
      tomcat: false
      jvm: true
      process: false
      hikaricp: false
      system: true
      jdbc: false
      http: true
      logback: false
      spring: true

